language: objective-c
osx_image: xcode8.2
script:
    'xcodebuild -scheme IosTravisFastlaneDemoDev -destination "platform=iOS Simulator,name=iPhone 7,OS=10.1" clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO'
