default_platform  :ios

desc "Test app"
lane :test do |options| #TDB
    scan
end

desc "Build and submit the app on Crashlytics Beta"
lane :dev do |options|
    scan
end

desc "Build and submit the app on Testflight"
lane :stage do |options| #TDB
end

desc "Build and submit the app on AppStore"
lane :prod do |options| #TDB
end

