default_platform  :ios

desc "Test app"
lane :test do |options|
    scan
end

desc "Build and submit the app on Crashlytics Beta"
lane :dev do |options|
    match(type: "adhoc")
    gym(scheme: "IosTravisFastlaneDemoDev")
end

desc "Build and submit the app on Testflight"
lane :stage do |options|
    match(type: "appstore")
    gym(scheme: "IosTravisFastlaneDemoStage")
end

desc "Build and submit the app on AppStore"
lane :prod do |options|
    match(type: "appstore")
    gym(scheme: "IosTravisFastlaneDemoProd")
    snapshot
end

